package edu.utap.movieapp.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp


data class Review (
    // Auth information
    var name: String = "",
    var ownerUid: String = "",
    //
    var text: String = "",
    var poster_path: String = "",
    var movieTitle: String = "",
    var releaseDate: String = "",
    @ServerTimestamp val timestamp: Timestamp? = null,
    //FirestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
    )